### ISSUE TITLE
小建议-希望发图的时候能有个关闭图片数据的功能

### ISSUE THREAD

**Issue by Rod-fish** [CCYellowStar/zhenxun_plugin_NovelAi#3]
主要是用ai绘图返回消息一堆参数群里人用不上，但是词条多消息多就顶消息顶的厉害，这个返回的图片数据能不能关掉呀，还有返回图片可不可以有回复对方词条的功能
小小的建议，大佬没有时间的话可以忽略（给大佬磕头

**Comment by Rod-fish** [comment]
还有就是，Stable Diffusioni图生图右边更多里面可以对图片进行等比缩放，就是相当于ai的超分，能不能emmm（磕头磕头

**Comment by CCYellowStar** [comment]
超分我是另外用了其他插件

**Comment by Rod-fish** [comment]
超分我试过，我的服务器运行超分有很多奇奇怪怪问题，目前NovelAi和bot不在同一个电脑运行，bot的电脑不能还用超分，所以我在想能不能用NovelAi的放大试试

**Comment by CCYellowStar** [comment]
效果没本地的好，不过我也是服务器跑，一张图要跑几分钟

**Comment by CCYellowStar** [comment]
我好像做不到at发送，我弄了队列之后发送的那个方法是可以指定发送的群号或者qq号的，但是那个方法里没有at，我如果用常规的发送虽然有at，但因为有队列，如果你在这个群发指令，然后那个群又发指令进入排队，会导致两次结果都发在最后请求的那个群里，所以目前我好像做不到at发送

**Comment by Rod-fish** [comment]
十分感谢大佬的回复，这个我想了一下确实是会有这个问题，那能不能设置在config关闭图片的数据信息或者消息折叠，因为图片tag多起来之后很容易顶消息（尤其是玩的人多排起队来弄之后，满屏全是图片数据信息，图片顶的太高了），可不可以回复的消息改成折叠的模式或者关闭回复图片tag等数据消息呢？这只是个小建议，这个问题不是很影响使用，主要是消息过多导致ai绘图画完都不知道对应的是哪一个人的绘画词条，这里有点影响，数据多起来就完全找不到了

**Comment by CCYellowStar** [comment]
要不改成转发形式




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月13日(星期二) 晚上7:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CCYellowStar/zhenxun_plugin_NovelAi] 小建议-希望发图的时候能有个关闭图片数据的功能 (Issue #3)





 
十分感谢大佬的回复，这个我想了一下确实是会有这个问题，那能不能设置在config关闭图片的数据信息或者消息折叠，因为图片tag多起来之后很容易顶消息（尤其是玩的人多排起队来弄之后，满屏全是图片数据信息，图片顶的太高了），可不可以回复的消息改成折叠的模式或者关闭回复图片tag等数据消息呢？这只是个小建议，这个问题不是很影响使用，主要是消息过多导致ai绘图画完都不知道对应的是哪一个人的绘画词条，这里有点影响，数据多起来就完全找不到了
