### ISSUE TITLE
第三方API挂了

### ISSUE THREAD

**Issue by Yukino-Stuki** [CCYellowStar/zhenxun_plugin_NovelAi#4]
http://lulu.uedbq.xyz/token文中这个地址进去以后就直接跳转到另一个网站，似乎用不了了

**Comment by CCYellowStar** [comment]
一个月前就挂了，作者摆烂了

**Comment by Yukino-Stuki** [comment]
了解，谢谢，请问还有类似刚好适配你的这个插件的api地址吗

1363923758
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCYellowStar/zhenxun_plugin_NovelAi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月29日(星期天) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCYellowStar/zhenxun_plugin_NovelAi] 第三方API挂了 (Issue #4)





 
一个月前就挂了，作者摆烂了

**Comment by CCYellowStar** [comment]
我也想问呢（）

**Comment by molanp** [comment]
建议自己搭个，我都是这样(

**Comment by CCYellowStar** [comment]
hk-01.starryfrp.com:51841
适配的本地版
