### ISSUE TITLE
怎么更改采样方式

### ISSUE THREAD

**Issue by skynetfly** [CCYellowStar/zhenxun_plugin_NovelAi#6]
默认的采样是euler,怎么更改采样方式呢，谢谢

**Comment by CCYellowStar** [comment]
这个得改我的代码里请求部分的参数

**Comment by skynetfly** [comment]
params = {
            "prompt": tag,
            "steps": 150,
            "negative_prompt": uTag,
            "seed": seed,
            "cfg_scale": 20.0,
            "width": W,
            "height": H
    }这一段没看到采样方式的参数

**Comment by CCYellowStar** [comment]
{
  "enable_hr": false,
  "denoising_strength": 0,
  "firstphase_width": 0,
  "firstphase_height": 0,
  "prompt": "",
  "styles": [
    "string"
  ],
  "seed": -1,
  "subseed": -1,
  "subseed_strength": 0,
  "seed_resize_from_h": -1,
  "seed_resize_from_w": -1,
  "batch_size": 1,
  "n_iter": 1,
  "steps": 50,
  "cfg_scale": 7,
  "width": 512,
  "height": 512,
  "restore_faces": false,
  "tiling": false,
  "negative_prompt": "string",
  "eta": 0,
  "s_churn": 0,
  "s_tmax": 0,
  "s_tmin": 0,
  "s_noise": 1,
  "override_settings": {},
  "sampler_index": "Euler"
}

**Comment by skynetfly** [comment]
非常感谢
