### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by tang-bai** [CCYellowStar/zhenxun_plugin_NovelAi#7]
![image](https://user-images.githubusercontent.com/71223830/223185950-e0e57752-50e0-4531-895a-04d98f2543a0.png)
这个是什么问题导致的
Python 3.8.9 (64-bit)

**Comment by CCYellowStar** [comment]
可能是最低支持3.9

**Comment by tang-bai** [comment]
我更新一下试试看
